### ISSUE TITLE
Project Inizilation

### ISSUE THREAD

**Issue by gokaySendil** [labadze/node-express-firebase-database-api#1]
Hi you answered my stackoverflow question with this project thank you firstly. My question was closed and could not return you. I am trying to run the project I hope I can do it thank you again.

**Comment by gokaySendil** [comment]
Should i post the items with google postman extension? I connected to server successfully.

**Comment by labadze** [comment]
Hello @gokaySendil  thanks for feedback.
So here few solutions as answer to your question.
Sorry for late response first of all.
In thins case you need to pass data in application json format.
It's better to pass your data via postman software. Ext(s) have some issues and first method is more clear.
You can use curl also (If you're familiar)

**Comment by labadze** [comment]
I'll add more explanation to answer:
For testing you can use postman or curl and it's good for debugging phase.
Then you need add integration, unit tests etc. I recommend to use jest for express or and mocha and chai.
Finally you'll use your front-end http module:

- For angular2 HttpClientModule
- For react Fetch 
- For Vue Axios

etc.
